language: python
python:
  - "2.6"
  - "2.7"
  
install:
  - sudo apt-get update
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade virtualenv
  - sudo apt-get install python-bs4
  - pip install BeautifulSoup4
  - pip install jinja2

script: 
  - nosetests ./tbc-python-web-crawler/testing/
